### ISSUE TITLE
Quotas are incorrect

### ISSUE THREAD

**Issue by drwahl** [alvise72/DroidStack#2]
When browsing "Quotas", all the maximum values seem to be incorrect (roughly double).  The used/consumed values are correct, however.  It is only the total/maximum values that are inaccurate.

**Comment by alvise72** [comment]
Still a problem with maximum security groups value which is returned incorrect by the API. It's value is actually the value of max security group rules. I'll disable its displaying temporary.

**Comment by alvise72** [comment]
Can this be considered as fixed ?

**Comment by drwahl** [comment]
Yes, the quotas look correct now.
